### ISSUE TITLE
can we use `devise gem` for authentication solution in pars stack?

### ISSUE THREAD

**Issue by rmros** [modernistik/parse-stack#11]
hi @apersaud  
can we use `devise gem` for authentication solution in pars stack?
what is your solution for authentication ?
how we can use gem with open stack? 
what things we need change those gem work as like before work?

**Comment by apersaud** [comment]
It is possible to combine some of `devise`'s capabilities with Parse-Stack in order to authenticate users. We are currently working on `login` and `session management` functionality for the new Parse-Server. The work is being done in the [login branch](https://github.com/modernistik/parse-stack/tree/login)
