### ISSUE TITLE
Undefined method `reset_password' for #<Parse::Client:0x007fadebd1ce50>

### ISSUE THREAD

**Issue by hspindell** [modernistik/parse-stack#15]
When calling
`Parse::User.request_password_reset("jarvis+232@gigtown.com")`

**Comment by apersaud** [comment]
Easy fix. Mark can handle it. The method signature has changed.

-- Anthony via Mobile

On Sep 29, 2016, at 5:03 PM, Henry Spindell <notifications@github.com>
wrote:

When calling
Parse::User.request_password_reset("jarvis+232@gigtown.com")

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/modernistik/parse-stack/issues/15>, or mute the thread

**Comment by apersaud** [comment]
While u guys are at it, can u add a unit test and make a pull request? Thx

-- Anthony via Mobile

On Sep 29, 2016, at 5:03 PM, Henry Spindell <notifications@github.com>
wrote:

When calling
Parse::User.request_password_reset("jarvis+232@gigtown.com")

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/modernistik/parse-stack/issues/15>, or mute the thread

**Comment by mstorch** [comment]
This is fixed and a unit test has been added for certain cases.
