### ISSUE TITLE
Batch save (save_all) method does not follow limit constraint

### ISSUE THREAD

**Issue by hspindell** [modernistik/parse-stack#25]
For example,  `User.save_all(limit: 1)` will trigger a save for all users rather than just one

**Comment by apersaud** [comment]
This is the expected behavior of using save_all as both `:updated_at` and `:limit` constraints are applied internally through the loop. `save_all` should not be when you need to apply either of those query constraints. `save_all` should be used when the object request count is greater than 1000.

Therefore the correct solution is:
```ruby
users = User.all(limit: 100) #
# modify your users
users.save # batch save
```
