### ISSUE TITLE
rails parse:upgrade not working correctly

### ISSUE THREAD

**Issue by whatsthebeef** [modernistik/parse-stack#28]
**Versions**

ruby 2.4.1p111
rails 5.1.1
parse-stack 1.6.11

**Issue**

When running `rails parse:upgrade` I see the error below in the terminal but the models I defined do seem to be created along with User and Role so it is creating the connection and I can also start up the rails app without an error. 

I have tried many different combinations of `Parse.setup` and also running the rails example you provide. All produce the same result.

I also tried running the same combination through the parse-console and get a similar message.

**Logs**

> rails parse:upgrade --trace
> ** Invoke parse:upgrade (first_time)
> ** Invoke parse:env (first_time)
> ** Execute parse:env
> ** Invoke environment (first_time)
> ** Execute environment
> ** Execute parse:upgrade
> Auto Upgrading Parse schemas...
> [+] Parse::Installation
> [Parse:ServiceUnavailableError] [E-1] POST schemas/_Installation :  (500)
> [Parse:Retry] Retries remaining 2 : POST schemas/_Installation
> [Parse:ServiceUnavailableError] [E-1] POST schemas/_Installation :  (500)
> [Parse:Retry] Retries remaining 1 : POST schemas/_Installation
> [Parse:ServiceUnavailableError] [E-1] POST schemas/_Installation :  (500)
> rails aborted!
> Parse::Error::ServiceUnavailableError: [E-1] POST schemas/_Installation :  (500)
> /Users/john/.rvm/gems/ruby-2.4.1/gems/parse-stack-1.6.11/lib/parse/client.rb:436:in `request'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/parse-stack-1.6.11/lib/parse/api/schema.rb:31:in `create_schema'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/parse-stack-1.6.11/lib/parse/model/core/schema.rb:59:in `create_schema'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/parse-stack-1.6.11/lib/parse/model/core/schema.rb:90:in `auto_upgrade!'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/parse-stack-1.6.11/lib/parse/model/object.rb:60:in `block in auto_upgrade!'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/parse-stack-1.6.11/lib/parse/model/object.rb:58:in `each'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/parse-stack-1.6.11/lib/parse/model/object.rb:58:in `auto_upgrade!'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/parse-stack-1.6.11/lib/parse/stack/tasks.rb:66:in `block (2 levels) in install_tasks'
> /Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
> /Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
> /Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
> /Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
> /Users/john/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
> /Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
> /Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
> /Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
> /Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
> /Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
> /Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
> /Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
> /Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/railties-5.1.1/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
> /Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/railties-5.1.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/railties-5.1.1/lib/rails/command.rb:46:in `invoke'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
> /Users/john/dev/pocketlab-labnotebook/bin/rails:9:in `require'
> /Users/john/dev/pocketlab-labnotebook/bin/rails:9:in `<top (required)>'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
> /Users/john/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
> /Users/john/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
> /Users/john/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
> /Users/john/dev/pocketlab-labnotebook/bin/spring:15:in `<top (required)>'
> bin/rails:3:in `load'
> bin/rails:3:in `<main>'
> Tasks: TOP => parse:upgrade

**From parse app**

> error: Class _Installation does not exist. code=103, message=Class _Installation does not exist.
> error: Error generating response. { code: 136, error: 'field GCMSenderId cannot be added' } code=136, error=field GCMSenderId cannot be added
> error: Uncaught internal server error. { code: 136, error: 'field GCMSenderId cannot be added' }
> [object Object]
> error: Error generating response. { code: 136, error: 'field GCMSenderId cannot be added' } code=136, error=field GCMSenderId cannot be added
> error: Uncaught internal server error. { code: 136, error: 'field GCMSenderId cannot be added' }
> [object Object]
> error: Error generating response. { code: 136, error: 'field GCMSenderId cannot be added' } code=136, error=field GCMSenderId cannot be added
> error: Uncaught internal server error. { code: 136, error: 'field GCMSenderId cannot be added' }
> [object Object]

**Comment by apersaud** [comment]
Hi John,

Can you verify that you are using version 1.6.12 and you are passing the
correct master key? That version has a fix for creating the Parse Server
Core classes.

On May 25, 2017, at 11:22 PM, John Bower <notifications@github.com> wrote:

*Versions*

ruby 2.4.1p111
rails 5.1.1
parse-stack 1.6.11

*Issue*

When running rails parse:upgrade I see the error below in the terminal but
the models I defined do seem to be created along with User and Role so it
is creating the connection and I can also start up the rails app without an
error.

I have tried many different combinations of Parse.setup and also running
the rails example you provide. All produce the same result.

I also tried running the same combination through the parse-console and get
a similar message.

*Logs*

rails parse:upgrade --trace
** Invoke parse:upgrade (first_time)
** Invoke parse:env (first_time)
** Execute parse:env
** Invoke environment (first_time)
** Execute environment
** Execute parse:upgrade
Auto Upgrading Parse schemas...
[+] Parse::Installation
[Parse:ServiceUnavailableError] [E-1] POST schemas/_Installation : (500)
[Parse:Retry] Retries remaining 2 : POST schemas/_Installation
[Parse:ServiceUnavailableError] [E-1] POST schemas/_Installation : (500)
[Parse:Retry] Retries remaining 1 : POST schemas/_Installation
[Parse:ServiceUnavailableError] [E-1] POST schemas/_Installation : (500)
rails aborted!
Parse::Error::ServiceUnavailableError: [E-1] POST schemas/_Installation :
(500)
/Users/john/.rvm/gems/ruby-2.4.1/gems/parse-stack-1.6.11/lib/parse/client.rb:436:in
request'
/Users/john/.rvm/gems/ruby-2.4.1/gems/parse-stack-1.6.11/lib/parse/api/schema.rb:31:in
create_schema'
/Users/john/.rvm/gems/ruby-2.4.1/gems/parse-stack-1.6.11/lib/parse/model/core/schema.rb:59:in
create_schema'
/Users/john/.rvm/gems/ruby-2.4.1/gems/parse-stack-1.6.11/lib/parse/model/core/schema.rb:90:in
auto_upgrade!'
/Users/john/.rvm/gems/ruby-2.4.1/gems/parse-stack-1.6.11/lib/parse/model/object.rb:60:in
block in auto_upgrade!'
/Users/john/.rvm/gems/ruby-2.4.1/gems/parse-stack-1.6.11/lib/parse/model/object.rb:58:in
each'
/Users/john/.rvm/gems/ruby-2.4.1/gems/parse-stack-1.6.11/lib/parse/model/object.rb:58:in
auto_upgrade!'
/Users/john/.rvm/gems/ruby-2.4.1/gems/parse-stack-1.6.11/lib/parse/stack/tasks.rb:66:inblock
(2 levels) in install_tasks'
/Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/task.rb:250:in
block in execute' /Users/john/.rvm/gems/ruby-2.4.1@global
/gems/rake-12.0.0/lib/rake/task.rb:250:ineach'
/Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/task.rb:250:in
execute' /Users/john/.rvm/gems/ruby-2.4.1@global
/gems/rake-12.0.0/lib/rake/task.rb:194:inblock in invoke_with_call_chain'
/Users/john/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in
mon_synchronize'
/Users/john/.rvm/gems/ruby-2.4.1@global
/gems/rake-12.0.0/lib/rake/task.rb:187:ininvoke_with_call_chain'
/Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/task.rb:180:in
invoke' /Users/john/.rvm/gems/ruby-2.4.1@global
/gems/rake-12.0.0/lib/rake/application.rb:152:ininvoke_task'
/Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:108:in
block (2 levels) in top_level' /Users/john/.rvm/gems/ruby-2.4.1@global
/gems/rake-12.0.0/lib/rake/application.rb:108:ineach'
/Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:108:in
block in top_level' /Users/john/.rvm/gems/ruby-2.4.1@global
/gems/rake-12.0.0/lib/rake/application.rb:117:inrun_with_threads'
/Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:102:in
top_level'
/Users/john/.rvm/gems/ruby-2.4.1/gems/railties-5.1.1/lib/rails/commands/rake/rake_command.rb:21:inblock
in perform'
/Users/john/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:178:in
standard_exception_handling'
/Users/john/.rvm/gems/ruby-2.4.1/gems/railties-5.1.1/lib/rails/commands/rake/rake_command.rb:18:in
perform'
/Users/john/.rvm/gems/ruby-2.4.1/gems/railties-5.1.1/lib/rails/command.rb:46:in
invoke'
/Users/john/.rvm/gems/ruby-2.4.1/gems/railties-5.1.1/lib/rails/commands.rb:16:in<top
(required)>'
/Users/john/dev/pocketlab-labnotebook/bin/rails:9:in require'
/Users/john/dev/pocketlab-labnotebook/bin/rails:9:in<top (required)>'
/Users/john/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in
load'
/Users/john/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in
call'
/Users/john/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client/command.rb:7:in
call'
/Users/john/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/client.rb:30:in
run'
/Users/john/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/bin/spring:49:in <top
(required)>'
/Users/john/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in
load'
/Users/john/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in
<top (required)>'
/Users/john/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in
require'
/Users/john/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in
require' /Users/john/dev/pocketlab-labnotebook/bin/spring:15:in<top
(required)>'
bin/rails:3:in load' bin/rails:3:in
'
Tasks: TOP => parse:upgrade

*From parse app*

error: Class _Installation does not exist. code=103, message=Class
_Installation does not exist.
error: Error generating response. { code: 136, error: 'field GCMSenderId
cannot be added' } code=136, error=field GCMSenderId cannot be added
error: Uncaught internal server error. { code: 136, error: 'field
GCMSenderId cannot be added' }
[object Object]
error: Error generating response. { code: 136, error: 'field GCMSenderId
cannot be added' } code=136, error=field GCMSenderId cannot be added
error: Uncaught internal server error. { code: 136, error: 'field
GCMSenderId cannot be added' }
[object Object]
error: Error generating response. { code: 136, error: 'field GCMSenderId
cannot be added' } code=136, error=field GCMSenderId cannot be added
error: Uncaught internal server error. { code: 136, error: 'field
GCMSenderId cannot be added' }
[object Object]

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/modernistik/parse-stack/issues/28>, or mute the thread

**Comment by whatsthebeef** [comment]
Yep, when I point it to HEAD it works fine. I should have checked. Cheers
