### ISSUE TITLE
Standard method of authentication using parse-stack

### ISSUE THREAD

**Issue by whatsthebeef** [modernistik/parse-stack#29]
This may seem like a dumb question but how do you propose the token/current user be managed so a browser client doesn't need to keep sending the username and password and so the current user is remembered by the server.

It looks like after the 'login' call and subsequent calls a session_token is being stored and reused in 'action.rb' but is this sufficient to allow for the web app to securely remember multiple concurrent users and be able to retrieve the appropriate User object when necessary? If not what do you recommend?

FYI I need to use the ACLs so can't just rely on the master_key

**Comment by apersaud** [comment]
In general, the session token is good enough to make Parse API requests on behalf of that user (as if you were that user). When a user is logged in, that session token is created by the server, and should be subsequently used for any action that you want to perform as that use since any action will utilize the allowed ACLs of that user on the operation. (Let me know if that makes sense). You do not need to use the master key to perform a query as the user, just pass the session token that you have stored: See https://github.com/modernistik/parse-stack#session for a few examples. Whenever you pass a user or a session token to a query, even if you've defined a master key in your configuration, it will ignore sending the master key and use the session token instead.

Normally for a web application, you should store this session token in your session cookie. On every landing page, you'd retrieve the session token stored in your cookie (ex. rails sessions) and utilize the `Parse::User.session` method to get the corresponding user back for that stored token:
```ruby
user = Parse::User.session(session_token)
```
The above request can also be cached temporarily (ex. 30 seconds) for faster performance in a web application as the user is bouncing between different pages until they log out (which you would call `user.logout` and delete the session token from the session cookie.

**Comment by whatsthebeef** [comment]
Yep, that makes sense. 

> Whenever you pass a user or a session token to a query, even if you've defined a master key in your configuration, it will ignore sending the master key and use the session token instead.

Is this applicable for create, update, delete operations on parse as well?

> The above request can also be cached temporarily (ex. 30 seconds) for faster performance in a web application

How is this different to storing the token in the session? How would you do it in Rails?

**Comment by apersaud** [comment]
> Is this applicable for create, update, delete operations on parse as well?
Yes for most API. - you will have to pass a session token: (see [actions API reference](http://www.rubydoc.info/github/modernistik/parse-stack/Parse/Actions), ex [`save`](http://www.rubydoc.info/github/modernistik/parse-stack/Parse/Actions#save-instance_method), [`destroy`](http://www.rubydoc.info/github/modernistik/parse-stack/Parse/Actions#destroy-instance_method))
```
session_token = user.session_token
myobject.save( session: session_token ) # create /update
myobject.destroy( session: session_token ) # delete
```

> How is this different to storing the token in the session? How would you do it in Rails?
It is not. I would store the Parse session token after you login the user into the rails session. 
```ruby
# somewhere in your controller
user.login(....) # assume success
session[:parse_session_token] = user.session_token
```
and when you want to retrieve the user in another controller
```ruby
# get the stored Parse session token from the rails session cookie
session_token = session[:parse_session_token] 
# fetch the user corresponding to this session token. 
user = Parse::User.session( session_token )
# if user is nil, then session expired or token doesn't exist.
```
So that is the general idea. However going to Parse Server everytime to fetch the user accross requests is very inefficient since we know the session is probably still valid, so you can cache the response for a certain amount of time instead of hitting Parse-Server every time. This only works if you've setup caching middleware for parse-stack (see [Caching](https://github.com/modernistik/parse-stack#cache) )
```ruby
# fetch or returned the cached user for this session_token.
user = Parse::User.session(session_token, cache: 30.seconds)
```
Of course you don't have to use the Parse-Stack caching middleware and you can use [Rails.cache](http://guides.rubyonrails.org/caching_with_rails.html) instead - same idea, your preference.

**Comment by apersaud** [comment]
> Also, would it therefore not be possible to implement a 'remember me' feature so the user wouldn't need to keep signing in?

That is the idea behind storing the Parse session token (in the example in the previous post) in the Rails session. Then in your before_action, see if there is a Parse session token stored in your `session` object - if there is, retrieve the user since they have already logged into your system - which is your 'Remember Me' feature.
